// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZUnr2tCgFsz2pYeyxQCFUWLm2yNbUck',
    appId: '1:693825567096:web:fb7e0a025938d7b59df08d',
    messagingSenderId: '693825567096',
    projectId: 'habit-8689a',
    authDomain: 'habit-8689a.firebaseapp.com',
    storageBucket: 'habit-8689a.firebasestorage.app',
    measurementId: 'G-X10MWETY62',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN20Mis5Nnf6qOAoIQ1mbforHbav8GKDg',
    appId: '1:693825567096:ios:10bd434e5bc27bd79df08d',
    messagingSenderId: '693825567096',
    projectId: 'habit-8689a',
    storageBucket: 'habit-8689a.firebasestorage.app',
    iosBundleId: 'com.davidfitzgerald.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN20Mis5Nnf6qOAoIQ1mbforHbav8GKDg',
    appId: '1:693825567096:ios:7771ae87691c4d1c9df08d',
    messagingSenderId: '693825567096',
    projectId: 'habit-8689a',
    storageBucket: 'habit-8689a.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );
}
